Use babe instead of aura for genesis
digicatapult/l3-flux-infra pull request #13
Opened 2023-08-30 12:11 UTC by jonmattgray

Retry of #9 

Update genesis scripts to use babe instead of aura. Chain spec has changed from:
```
      "aura": {
        "authorities": [
          "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
          "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty",
          "5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y"
        ]
      },
```
to
```
      "babe": {
        "authorities": [
          [
            "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
            1
          ],
          [
            "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty",
            1
          ],
          [
            "5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y",
            1
          ]
        ],
        "epochConfig": {
          "c": [
            1,
            4
          ],
          "allowed_slots": "PrimaryAndSecondaryPlainSlots"
        }
```

2023-09-04 08:39 UTC, mattdean-digicatapult submitted a review, later dismissed
lgtm

2023-09-12 07:41 UTC, dblane-digicatapult requested changes
In all the `kustomize.toolkit.fluxcd.io/v1` references you need to remove `validation: client` as this is no longer a part of the API spec and causing the kustomizations to fail.

2023-09-13 08:22 UTC, dblane-digicatapult submitted a review, later dismissed
Looks good to me.

2023-09-13 08:43 UTC, dblane-digicatapult approved these changes

2023-09-13 09:02 UTC, merged